services:
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    volumes:      
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
volumes:
  postgres_data: