networks:
  web:
    external: true
  internal:
    external: false

services:
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - traefik.http.routers.django.rule=Host(`api.recursoshidricos.pt`)
      - traefik.http.routers.django.tls=true
      - traefik.http.routers.django.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    expose:
      - 80
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - internal
volumes:
  postgres_data: