networks:
  web:
    external: true
  internal:
    external: false

services:
  backend:
    container_name: backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/logs:/code/logs
    labels:
      - traefik.http.routers.backend.rule=Host(`api.recursoshidricos.pt`)
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    expose:
      - 80
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - internal
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    expose:
      - "5050"
    labels:
      - traefik.http.routers.pgadmin.rule=Host(`db-admin.recursoshidricos.pt`)
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=lets-encrypt
      - traefik.port=5050
    networks:
      - internal
      - web

volumes:
  postgres_data: