# Generated by Django 4.0.3 on 2022-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="psa",
            name="last_updated",
            field=models.DateTimeField(null=True),
        ),
    ]
