# Generated by Django 4.0.3 on 2022-04-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_psa_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psa',
            options={'verbose_name': 'Parameter Station Assignment', 'verbose_name_plural': 'Parameter Station Assignments'},
        ),
    ]
