# Generated by Django 4.0.3 on 2022-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_last_updated_psa_data_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="last_update",
            field=models.DateTimeField(null=True),
        ),
    ]
